---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "Homer"
subtitle: "arin innovation"
logo: "assets/icons/arin_blanco.png"

header: false
footer: <a href="/#cx"> Customer Experience </a> | <a href="/#ebs"> E-Business Suite </a> | <a href="/#erp"> ERP Cloud </a> | <a href="/#jde"> JD Edwards </a>


columns: "2"
connectivityCheck: false
# Optional theme customization
theme: default

# Optional custom stylesheet
# Will load custom CSS files. Especially useful for custom icon sets.
stylesheet:
   - "assets/custom.css"


colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link-hover: "#ffdd57"

links:
  - name: "Home"
    icon: "fas fa-home"
    url: "#"
  - name: "HelpDesk"
    icon: "fas fa-circle-check"
    url: "https://helpdesk.arin-innovation.com"
    target: "_blank" # optional html tag target attribute
  - name: "sysPass"
    icon: "fas fa-lock"
    url: "http://syspass.arin.local/syspass/"
    target: "_blank" # optional html tag target attribute
  - name: "ariNet"
    icon: "fas fa-folder-open"
    url: "http://arinet.arin.local:8010/ariNet_v2/"
    target: "_blank" # optional html tag target attribute
  - name: "Guacamole"
    icon: "fas fa-desktop"
    url: "https://guacamole.arin.local"
    target: "_blank" # optional html tag target attribute
  - name: "arInOut"
    icon: "fas fa-clock"
    url: "http://intranet.arin.local/ords/f?p=arinout"
    target: "_blank" # optional html tag target attribute
  - name: "aRHin"
    icon: "fas fa-sign-in"
    url: "http://intranet.arin.local/ords/f?p=vacaciones"
    target: "_blank" # optional html tag target attribute
  - name: "arinPage"
    icon: "fas fa-address-book"
    url: "http://intranet.arin.local/ords19/f?p=ARINPAGE"
    target: "_blank" # optional html tag target attribute
  - name: "GitLab"
    icon: "fas fa-code"
    url: "http://gitlab.arin.local"
    target: "_blank" # optional html tag target attribute
  - name: "Metalink"
    icon: "fas fa-question-circle"
    url: "https://support.oracle.com/epmos/faces/Dashboard"
    target: "_blank" # optional html tag target attribute

# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - items:
      - logo: "https://objectstorage.eu-frankfurt-1.oraclecloud.com/n/ax0ecu9fxbma/b/homer-files/o/logos_png%2Fcx.png"
        url: "/#cx"
  - items:
      - logo: "https://objectstorage.eu-frankfurt-1.oraclecloud.com/n/ax0ecu9fxbma/b/homer-files/o/logos_png%2Febs.png"
        url: "/#ebs"
  - items:
      - logo: "https://objectstorage.eu-frankfurt-1.oraclecloud.com/n/ax0ecu9fxbma/b/homer-files/o/logos_png%2Ferp.png"
        url: "/#erp"
  - items:
      - logo: "https://objectstorage.eu-frankfurt-1.oraclecloud.com/n/ax0ecu9fxbma/b/homer-files/o/logos_png%2Fjde.png"
        url: "/#jde"


